### PR TITLE
Switch to Hid.Net

### PR DESCRIPTION
**Pull request by MelbourneDeveloper**
This pull request removes the HidLibrary dependency and replaces it with the Hid.Net dependency. The units tests have been split between .NET 4.5.2, and .NET Core 2.0. There should be no breaking changes in .NET 4.5.2 because this code will remain specific to Windows. However, the .NET Standard 2.0 DLL removes some functionality and therefore there are some #ifs for the two versions. 

To see where code is different across the two platforms, have a look at GetLedgerAsync in NanoSTests.

### CODE REVIEW

**Comment by MelbourneDeveloper** [comment]
Note: Version 1.1.3 of the Hid.Net NuGet is still indexing...  So, there may be compile problems until it arrives in the NuGet gallery. It usually doesn't take long.

**Comment by NicolasDorier** [comment]
will review today, awesome!

**Comment by MelbourneDeveloper** [comment]
@NicolasDorier , it's my sunday today so if you let me know soon, I might be able to fix anything before work tomorrow. Also, Github says there are conflicts, but that is not right. I have manually compared the files and they are as close as possible. Github is saying that things are different when they are actually not.

**Comment by MelbourneDeveloper** [comment]
There is a problem with Github's merging at the moment. It says my master branch is totally different to your master branch. It's basically saying that your master branch does not contain the pull request that I made so when I compare, everything is different, and the flow on effect is that I can't resolve the conflicts.

**Comment by MelbourneDeveloper** [comment]
Any thoughts on this @NicolasDorier ?

**Comment by NicolasDorier** [comment]
I see you are using `NETSTANDARD2_0` while not targetting it? Why?

That said, `netstandard2.0` and `netcoreapp2.1` should be supported. (We might need to disable HID lib in this case, which is fine) 
I use this lib in a netcoreapp2.1 project with a custom transport which use websocket => HID bridge.

**Comment by MelbourneDeveloper** [comment]
Hi. Hid.Net and LedgerWallet definitely targets .NET Standard 2.0. The projects compile to both platforms.

image

image

The unit test project I created is .NET Core 2.0 so it should be supported in 2.1

image

I definitely want to support Websocket => HID bridges so if you point me to the project, I will check to see how i can be implemented. Hid.Net has a simple interface with byte[] ReadAsync() and WriteAsync(byte[]) . There is no problem with using a http client.

There is no need to disable HID lib in .NET Standard or .NET Core. But, the use of this library is done with dependency injection. It is only used for Windows classic. It is not used for Android, or UWP. These platforms have their own Hid libraries.

**Comment by NicolasDorier** [comment]
Testing it now, this is an awesome job I am excited, merging soon.

**Comment by NicolasDorier** [comment]
Merged on https://github.com/LedgerHQ/ledger-dotnet-api/commit/97b70ad4eefbb850d7519c3eeab144a8e0cc0423 I squashed and cleaned up some warning. Will push nuget package shortly.

**Comment by NicolasDorier** [comment]
Ah U2F do not work anymore.

**Comment by NicolasDorier** [comment]
Tomorrow I will do a refactor such that we have same branches for both NETSTANDARD and not NETSTANDARD, and a solution to simplify your life for Android integration.

**Comment by MelbourneDeveloper** [comment]
> Ah U2F do not work anymore.

@NicolasDorier sorry about that.  I wasn't sure how to test that. I only have an NanoS . I wasn't really sure what U2F was. I looked at this website: https://www.yubico.com/solutions/fido-u2f/ but didn't really understand how it relates to the Ledger. I will try to fix this when I have time.

> I will do a refactor such that we have same code branches for both NETSTANDARD and not NETSTANDARD, and a solution to simplify your life for Android integration.

OK. Let me know if there's anything I can do to save you time. The reason I split the code was that I didn't want to break the existing .NET Framework implementation. The .NET Standard implementation needs to support multiple implementations so I removed the LedgerClient.GetHIDLedgers() method because that is the main thing that cannot sit across the three platforms.

**Comment by MelbourneDeveloper** [comment]
Good question. Basically the devices (Trezor and Ledger) both expect 65 bytes instead of 64. For some reason, they expect a zero in the first byte. However , the Android Hid library automatically strips this out and I can't control it. So, if I send 64 bytes, it doesn't work. So, the workaround is to make the other implementations behave in the same way as the Android library, but allow for other scenarios with the flag.

**Comment by MelbourneDeveloper** [comment]
I could move the workaround in to the Android implementation though...

**Comment by NicolasDorier** [comment]
I will soon commit something which would allow you to cleanly add other implementation.

**Comment by MelbourneDeveloper** [comment]
Ok. But Hid.Net still needs to do it for Trezor as well.

**Comment by MelbourneDeveloper** [comment]
This sounds good. So, you have taken a dependency injection approach? That's definitely a good idea.

Hoping to grab this and add the Android stuff tomorrow night, but over the weekend at the latest.

**Comment by MelbourneDeveloper** [comment]
@NicolasDorier , this line can't really be implemented on Android:

`IHIDDevice CreateFromDescription(HIDDeviceInformation decription);`

Device information is different from platform to platform. For example, DevicePath is basically a Windows specific thing and that is why Hid.Net doesn't implement it as a part of the interface.

**Comment by NicolasDorier** [comment]
@MelbourneDeveloper Just set an empty string to `DevicePath` for android.

**Comment by MelbourneDeveloper** [comment]
I will try but I doubt I can do anything with this.

**Comment by NicolasDorier** [comment]
what do you doubt? I am taking no assumption on the underlying shape of HID library.

**Comment by MelbourneDeveloper** [comment]
The connection mechanism is different. I have already posted the Android code several times. 

   private void RegisterReceiver()
       {
           try
           {
               lock (_ReceiverLock)
               {
                   if (_UsbDeviceAttachedReceiver != null)
                   {
                       UnregisterReceiver(_UsbDeviceAttachedReceiver);
                       _UsbDeviceAttachedReceiver.Dispose();
                   }

                   _UsbDeviceAttachedReceiver = new UsbDeviceAttachedReceiver(_LedgerHidDevice);
                   RegisterReceiver(_UsbDeviceAttachedReceiver, new IntentFilter(UsbManager.ActionUsbDeviceAttached));

                   if (_UsbDeviceDetachedReceiver != null)
                   {
                       UnregisterReceiver(_UsbDeviceDetachedReceiver);
                       _UsbDeviceDetachedReceiver.Dispose();
                   }

                   _UsbDeviceDetachedReceiver = new UsbDeviceDetachedReceiver(_LedgerHidDevice);
                   RegisterReceiver(_UsbDeviceDetachedReceiver, new IntentFilter(UsbManager.ActionUsbDeviceDetached));
               }
           }
           catch (Exception ex)
           {
           }
       }

I can't just enumerate devices and then request connection. But I will see what I can do. 

Another problem is ... What if the device is not connected at the time of calling CreateFromDescription? CreateFromDescription works fine on Windows in a controlled unit test but in other situations, the code will need to poll it again and again until the device is connected.

**Comment by NicolasDorier** [comment]
@MelbourneDeveloper you can.

Just attach, and keep in a locked list what get attached and detached, and make the provider return that list synchronously.

> Another problem is ... What if the device is not connected at the time of calling CreateFromDescription? CreateFromDescription works fine on Windows in a controlled unit test but in other situations, the code will need to poll it again and again until the device is connected.

I doubt it will happen, as `CreateFromDescription` will be called only if it is in the above locked list.

**Comment by MelbourneDeveloper** [comment]
I will do my best.

**Pull request closed without merging**
