### PR TITLE
Exception Handling Fix

### PR DESCRIPTION
**Pull request by MelbourneDeveloper**
Handle the case where the underlying library throws an exception so that RenewTransportAsync is called

### CODE REVIEW

**Comment by MelbourneDeveloper** [comment]
@NicolasDorier this change exists in both pull requests but even if the other pull request is not accepted, this one is important for existing code.

**Comment by NicolasDorier** [comment]
Please, fix `RenewTransportAsync` instead to not throw. If we catch here we are suppressing any important information to the debugger.

**Comment by MelbourneDeveloper** [comment]
There's nothing wrong with RenewTransportAsync. The problem is when the underlying layer throws and exception. If you want to keep the information, it needs to go in a log.

**Comment by MelbourneDeveloper** [comment]
The other option is to deal with it at a higher level but the library is explicitly designed to handle failure by calling RenewTransportAsync

**Comment by NicolasDorier** [comment]
What should happen is the following: If you call and it throws, it should then try to renew the transport.

If this time it throws, you should not attempt to catch it.

**Comment by MelbourneDeveloper** [comment]
That's exactly what I did. If the underlying layer throws an exception, it will catch it and return null. If null is returned, it will trigger RenewTransportAsync. That's how the original code works. The change makes the code work the original code works.

**Comment by NicolasDorier** [comment]
This is ugly, what about try/catch inside the `Exchange` method, and only for the first call to `ExchangeCore`? So we don't catch potentially important errors from underlying provider.

**Comment by MelbourneDeveloper** [comment]
It's up to you.

**Comment by MelbourneDeveloper** [comment]
@nicolasdorier I completely agree that exceptions should not be swallowed. I agree that if the library throws an exception, the highest level code should be given a choice what to do. For example, if the app sends a message and there is no response, the app should decide what to do. 

Reconnect?

Tell the user there was an error? 

Log it? 

Reconnect and send the same message? 

All these things are legitimate. But even before my changes, it was calling RenewTransport. What this does is removes control from the highest level code and removes visibility of any underlying problems. It makes the assumption that the ledger is still connected when maybe it's not there...

**Comment by NicolasDorier** [comment]
So the no response was specific of `hid.dll`. What does HidLibrary.NET throw if it get disconnected and you try to read it?

**Comment by MelbourneDeveloper** [comment]
It's not specific to hid.dll _per se_.  HidLibrary seems to return null in that case, but Hid.Net will throw an exception. It's because, if something goes wrong, the highest level code should decide what to do immediately, and the low level code shouldn't try to continue...

But, I can change Hid.Net so that there is no exception thrown. That way the catch block is not necessary for most situations. However, if some unexpected scenario comes up, an exception may be thrown for some other reason. The high level code should definitely do something about it.

**Comment by NicolasDorier** [comment]
@MelbourneDeveloper what type of exception? A catch all is really bad.

**Comment by MelbourneDeveloper** [comment]
Good point. I think it's probably just an Exception. But, it should be a better exception. I will change Hid.Net to throw a more useful exception. 

However, your code should be agnostic of my code. If you handle my exception, it will be tying your code to my code even more closely. You will need to do even more abstraction.

**Comment by MelbourneDeveloper** [comment]
I can also just return null like HidLibrary...

But, I don't really like this approach.

**Comment by MelbourneDeveloper** [comment]
A catch all is necessary because if someone is using a different library, there is no way to know what it will do... It might return null, it might throw and exception. Anything could happen.

**Comment by NicolasDorier** [comment]
Or just do like the `Read` where you catch `HIDDeviceException` if anything else is thrown, this is a bug and should be handled inside the `IHidDevice` implementation.

**Comment by NicolasDorier** [comment]
please just do like I did in the read, catching the HID exception.

**Comment by MelbourneDeveloper** [comment]
@NicolasDorier, sorry I'm not going to get a chance to work on this for a while, but feel free to change what I've done.

**Comment by NicolasDorier** [comment]
will check today

**Comment by NicolasDorier** [comment]
ah ok actually just package update now

**Pull request merged**
